FROM node:18-alpine

WORKDIR /app

COPY . .

RUN npm install -g snyk 
RUN npm install snyk-to-html -g

RUN --mount=type=secret,id=snyk_token \
    export SNYK_AUTH_TOKEN=$(cat /run/secrets/snyk_token) && \
    snyk auth $SNYK_AUTH_TOKEN


ARG OUTPUT_FILENAME
ENV OUTPUT_FILENAME=$OUTPUT_FILENAME

RUN snyk auth $SNYK_AUTH_TOKEN && snyk test --json | snyk-to-html -o $OUTPUT_FILENAME.html || true